In [16]:
from unittest import result

import pandas as pd
import numpy as np
import re
import unicodedata

from pandas.core.computation.parsing import tokenize_string

FILENAME = "../x-24-us-election/part_1/may_july_chunk_1.csv.gz"

In [17]:

df = pd.read_csv(FILENAME)

df

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,False,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,False,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,False,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,False,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,1801001192861974976,#BattleForNumber10\nConservative one of you is...,https://twitter.com/Dyslexpolitics/status/1801...,1.718227e+09,"[{'display_url': 'pic.x.com/ayw3epkeob', 'expa...",False,NaN,NaN,1801001192861974976,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1507014876220178437, 'id_str': '1507014...",2024-06-12,NaN,tweet-
49996,49996,1801001192501191105,Option A: vote for Trump (and are white) - you...,https://twitter.com/HarvardTwins/status/180100...,1.718227e+09,[],False,NaN,NaN,1801001192501191105,...,True,NaN,NaN,NaN,NaN,NaN,"{'id': 1673014548742426624, 'id_str': '1673014...",2024-06-12,NaN,tweet-
49997,49997,1801001192194998392,@Billy_Doan06 @NikolaBench @Maga_BrettCTO 🚀🚀🚀,https://twitter.com/CatskillCrypto/status/1801...,1.718227e+09,[],False,NaN,NaN,1801001192194998392,...,False,BIGSTARR0609,1.800996e+18,1.746974e+18,NaN,NaN,"{'id': 1591877040390692864, 'id_str': '1591877...",2024-06-12,NaN,tweet-
49998,49998,1801001192191045935,@The_Patriot9 @GOP @BPUnion Yea guy kids weren...,https://twitter.com/AlwaysFaithful0/status/180...,1.718227e+09,[],False,NaN,NaN,1801001192191045935,...,False,The_Patriot9,1.801001e+18,1.460782e+18,NaN,NaN,"{'id': 1324077429015547905, 'id_str': '1324077...",2024-06-12,NaN,tweet-
49999,49999,1801001191695925292,"@WCCO You can’t lump them together! Is Trump,...",https://twitter.com/SnazBj/status/180100119169...,1.718227e+09,[],False,NaN,NaN,1801001191695925292,...,False,WCCO,1.800985e+18,1.300087e+07,NaN,NaN,"{'id': 1274353224913428481, 'id_str': '1274353...",2024-06-12,NaN,tweet-

In [7]:
df = df.replace(r'\xa0', ' ', regex=True)
en = df[df['lang'] == 'en']
en

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,False,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,False,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,False,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,False,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,49993,1801001195894423570,@maliktheoracle Crazy how I’m seeing everyone ...,https://twitter.com/shiroto1220/status/1801001...,1.718227e+09,[],False,NaN,NaN,1801001195894423570,...,False,maliktheoracle,1.800632e+18,8.819100e+17,NaN,NaN,"{'id': 1052715545701826626, 'id_str': '1052715...",2024-06-12,NaN,tweet-
49995,49995,1801001192861974976,#BattleForNumber10\nConservative one of you is...,https://twitter.com/Dyslexpolitics/status/1801...,1.718227e+09,"[{'display_url': 'pic.x.com/ayw3epkeob', 'expa...",False,NaN,NaN,1801001192861974976,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1507014876220178437, 'id_str': '1507014...",2024-06-12,NaN,tweet-
49996,49996,1801001192501191105,Option A: vote for Trump (and are white) - you...,https://twitter.com/HarvardTwins/status/180100...,1.718227e+09,[],False,NaN,NaN,1801001192501191105,...,True,NaN,NaN,NaN,NaN,NaN,"{'id': 1673014548742426624, 'id_str': '1673014...",2024-06-12,NaN,tweet-
49998,49998,1801001192191045935,@The_Patriot9 @GOP @BPUnion Yea guy kids weren...,https://twitter.com/AlwaysFaithful0/status/180...,1.718227e+09,[],False,NaN,NaN,1801001192191045935,...,False,The_Patriot9,1.801001e+18,1.460782e+18,NaN,NaN,"{'id': 1324077429015547905, 'id_str': '1324077...",2024-06-12,NaN,tweet-
49999,49999,1801001191695925292,"@WCCO You can’t lump them together! Is Trump,...",https://twitter.com/SnazBj/status/180100119169...,1.718227e+09,[],False,NaN,NaN,1801001191695925292,...,False,WCCO,1.800985e+18,1.300087e+07,NaN,NaN,"{'id': 1274353224913428481, 'id_str': '1274353...",2024-06-12,NaN,tweet-

In [8]:
def clean_tweet(df):
    df['cleanedTweet'] = df['rawContent'].str.normalize('NFKD')
    df['cleanedTweet'] = df['cleanedTweet'].astype(str).str.replace(r'(\n)', lambda m: "",regex=True).str.strip()
    df['cleanedTweet'] = df['cleanedTweet'].str.replace(r"^.{0,5}(@\S*\b\s)+|(https:\S*\b)",lambda m: "",regex=True)
    df['cleanedTweet'] = df['cleanedTweet'].str.replace(r'\s+', ' ', regex=True)
    return df

clean_tweet(en)

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type,cleanedTweet
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-,I cant imagine anyone actually feels this way....
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-,Voters can also sway me away from voting for s...
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-,Can you name that amount of charges brought ag...
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-,The fact remains that Joe Biden is simply a te...
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-,That's funny you're obviously trying to coveru...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,49993,1801001195894423570,@maliktheoracle Crazy how I’m seeing everyone ...,https://twitter.com/shiroto1220/status/1801001...,1.718227e+09,[],False,NaN,NaN,1801001195894423570,...,maliktheoracle,1.800632e+18,8.819100e+17,NaN,NaN,"{'id': 1052715545701826626, 'id_str': '1052715...",2024-06-12,NaN,tweet-,Crazy how I’m seeing everyone blame the black ...
49995,49995,1801001192861974976,#BattleForNumber10\nConservative one of you is...,https://twitter.com/Dyslexpolitics/status/1801...,1.718227e+09,"[{'display_url': 'pic.x.com/ayw3epkeob', 'expa...",False,NaN,NaN,1801001192861974976,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1507014876220178437, 'id_str': '1507014...",2024-06-12,NaN,tweet-,#BattleForNumber10Conservative one of you is v...
49996,49996,1801001192501191105,Option A: vote for Trump (and are white) - you...,https://twitter.com/HarvardTwins/status/180100...,1.718227e+09,[],False,NaN,NaN,1801001192501191105,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1673014548742426624, 'id_str': '1673014...",2024-06-12,NaN,tweet-,Option A: vote for Trump (and are white) - you...
49998,49998,1801001192191045935,@The_Patriot9 @GOP @BPUnion Yea guy kids weren...,https://twitter.com/AlwaysFaithful0/status/180...,1.718227e+09,[],False,NaN,NaN,1801001192191045935,...,The_Patriot9,1.801001e+18,1.460782e+18,NaN,NaN,"{'id': 1324077429015547905, 'id_str': '1324077...",2024-06-12,NaN,tweet-,Yea guy kids weren't not allowed to go to scho...
49999,49999,1801001191695925292,"@WCCO You can’t lump them together! Is Trump,...",https://twitter.com/SnazBj/status/180100119169...,1.718227e+09,[],False,NaN,NaN,1801001191695925292,...,WCCO,1.800985e+18,1.300087e+07,NaN,NaN,"{'id': 1274353224913428481, 'id_str': '1274353...",2024-06-12,NaN,tweet-,"You can’t lump them together! Is Trump, who ra..."

In [9]:
explosion = en.explode('mentionedUsers').reset_index(drop=True)
dict_series = explosion['mentionedUsers'].apply(lambda x: x if isinstance(x, list) else {})
normed = pd.json_normalize(dict_series)
#result = pd.concat([explosion['id'], normed[['name','screen_name']]], axis=1)
#result
explosion

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type,cleanedTweet
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-,I cant imagine anyone actually feels this way....
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-,Voters can also sway me away from voting for s...
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-,Can you name that amount of charges brought ag...
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-,The fact remains that Joe Biden is simply a te...
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-,That's funny you're obviously trying to coveru...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44991,49993,1801001195894423570,@maliktheoracle Crazy how I’m seeing everyone ...,https://twitter.com/shiroto1220/status/1801001...,1.718227e+09,[],False,NaN,NaN,1801001195894423570,...,maliktheoracle,1.800632e+18,8.819100e+17,NaN,NaN,"{'id': 1052715545701826626, 'id_str': '1052715...",2024-06-12,NaN,tweet-,Crazy how I’m seeing everyone blame the black ...
44992,49995,1801001192861974976,#BattleForNumber10\nConservative one of you is...,https://twitter.com/Dyslexpolitics/status/1801...,1.718227e+09,"[{'display_url': 'pic.x.com/ayw3epkeob', 'expa...",False,NaN,NaN,1801001192861974976,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1507014876220178437, 'id_str': '1507014...",2024-06-12,NaN,tweet-,#BattleForNumber10Conservative one of you is v...
44993,49996,1801001192501191105,Option A: vote for Trump (and are white) - you...,https://twitter.com/HarvardTwins/status/180100...,1.718227e+09,[],False,NaN,NaN,1801001192501191105,...,NaN,NaN,NaN,NaN,NaN,"{'id': 1673014548742426624, 'id_str': '1673014...",2024-06-12,NaN,tweet-,Option A: vote for Trump (and are white) - you...
44994,49998,1801001192191045935,@The_Patriot9 @GOP @BPUnion Yea guy kids weren...,https://twitter.com/AlwaysFaithful0/status/180...,1.718227e+09,[],False,NaN,NaN,1801001192191045935,...,The_Patriot9,1.801001e+18,1.460782e+18,NaN,NaN,"{'id': 1324077429015547905, 'id_str': '1324077...",2024-06-12,NaN,tweet-,Yea guy kids weren't not allowed to go to scho...
44995,49999,1801001191695925292,"@WCCO You can’t lump them together! Is Trump,...",https://twitter.com/SnazBj/status/180100119169...,1.718227e+09,[],False,NaN,NaN,1801001191695925292,...,WCCO,1.800985e+18,1.300087e+07,NaN,NaN,"{'id': 1274353224913428481, 'id_str': '1274353...",2024-06-12,NaN,tweet-,"You can’t lump them together! Is Trump, who ra..."

In [37]:
import ast
#en['mentionedUsers'] = en['mentionedUsers'].apply(lambda x: ast.literal_eval(x))
# 1. Explode the list (missing rows are safely kept as NaN)
exploded_df = en.explode('mentionedUsers').reset_index(drop=True)

# 2. Fill NaN rows with an empty dict so json_normalize doesn't fail
dict_series = exploded_df['mentionedUsers'].apply(lambda x: x if isinstance(x, dict) else {})

# 3. Normalize the dictionaries into columns
normalized_cols = pd.json_normalize(dict_series)

# 4. Combine the ID with the extracted values
result = pd.concat([exploded_df['id'], normalized_cols[['name', 'screen_name']]], axis=1)

users = result.groupby(['screen_name','name']).agg(count =('screen_name','size'))
users

                              count
screen_name  name
0000000007Y  Mamaceqtaw           1
001_lisa_    Lisa 001             1
01Funkytown  .*Funkytown™*.       3
01IOTA       Brother Eric         4
01splcheck   Stephen              1
...                             ...
zuzu447      Susanna Heimann      1
zuzupetals09 zuzupetals09         1
zvonimirtot  Zvonimir Tot         1
zxck_vro     𝙕 𝙓 𝘾 𝙆 👁️           1
zypisfy      Kiuku                8

[16366 rows x 1 columns]

In [9]:
pd.read_csv("../DataFiles/combined_output.csv")

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,inReplyToTweetId,inReplyToTweetIdStr,inReplyToUser,source,sourceUrl,sourceLabel,card,cashtags,place,epoch_dt
0,0.0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1.801042e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,1801350289112633493,@SUBRATA30016572 YES!,https://twitter.com/maga9241/status/1801350289...,1.718310e+09,[],False,NaN,NaN,1.801350e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,1801321015319896315,"@BidenHQ Thank you, PM Meloni, for shepherding...",https://twitter.com/jeannieCsylvia/status/1801...,1.718303e+09,[],False,NaN,NaN,1.801321e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,1801287600910561322,@crismiller12 OMG 🤦‍♂️,https://twitter.com/Joey_S45/status/1801287600...,1.718295e+09,[],False,NaN,NaN,1.801288e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,1801251973691256875,"Trump won't tax your TIPS! Biden wants your ""...",https://twitter.com/RubyMcKayOnline/status/180...,1.718287e+09,[],False,NaN,NaN,1.801252e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,0.0,1811943404097740986,@SunBeltLAM @DreamLeaf5 @nykyt0sha Having a si...,https://twitter.com/Fearthecow93/status/181194...,1.720836e+09,PW,False,NaN,NaN,1.811943e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,0.0,1811916255323939198,Watch! Putin's Comments on Trump Saying He Wil...,https://twitter.com/R_J_Drake_2028/status/1811...,1.720829e+09,PW,False,NaN,NaN,1.811916e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,0.0,1813717720619446733,@jwn0001 @EpochTimes Justice Gorsuch agrees wi...,https://twitter.com/QuietMan1953/status/181371...,1.721259e+09,[],False,NaN,NaN,1.813718e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,0.0,1813702073260949648,@LauraLoomer Joe biden says he has covid,https://twitter.com/MacawSam7401/status/181370...,1.721255e+09,[],False,NaN,NaN,1.813702e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,0.0,1813681140047270067,"Donald Trump, in a wide-ranging interview at M...",https://twitter.com/markets/status/18136811400...,1.721250e+09,[],False,NaN,NaN,1.813681e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
pd.read_csv("../fixed/octobergap_chunk_14.csv")

,id,text,epoch,media,retweetedTweet,lang,rawContent,replyCount,retweetCount,likeCount,...,hashtags,mentionedUsers,links,viewCount,quotedTweet,in_reply_to_screen_name,location,user,date,week
0,1845101673116495971,@FishDaddy1392 @nfr_podcast Most of those repo...,1728741493,PW,False,en,@FishDaddy1392 @nfr_podcast Most of those repo...,0,0,0,...,[],"[{'id_str': '1745113320393187328', 'name': 'St...",[],PW,False,PW,PW,"{'id': 1730253438913544192, 'id_str': '1730253...",2024-10-12,23
1,1845101672810377618,Trump should use this speech by Michael Moore ...,1728741493,PW,False,en,Trump should use this speech by Michael Moore ...,2,1,0,...,"[{'indices': [185, 195], 'text': 'Trump2024'},...",[],[],PW,True,PW,PW,"{'id': 386918403, 'id_str': '386918403', 'url'...",2024-10-12,23
2,1845101671216505206,"@MeghanMcCain JM, if he were honest, would wei...",1728741493,PW,False,en,"@MeghanMcCain JM, if he were honest, would wei...",0,0,0,...,[],"[{'id_str': '23176276', 'name': 'Meghan McCain...",[],PW,False,PW,PW,"{'id': 1404504029829468165, 'id_str': '1404504...",2024-10-12,23
3,1845101666753986946,@MissouriSquirrl @antixxx0007 @america Biden's...,1728741492,PW,False,en,@MissouriSquirrl @antixxx0007 @america Biden's...,0,0,4,...,[],"[{'id_str': '1560418533229592576', 'name': 'Mi...",[],PW,False,PW,PW,"{'id': 1599013444992528386, 'id_str': '1599013...",2024-10-12,23
4,1845101665071824919,@nypost Kamala &amp; the Dems. were saying Bid...,1728741491,PW,False,en,@nypost Kamala &amp; the Dems. were saying Bid...,0,0,0,...,[],"[{'id_str': '17469289', 'name': 'New York Post...",[],PW,False,PW,PW,"{'id': 1791632345583300608, 'id_str': '1791632...",2024-10-12,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42683,1845580110419890341,@iAnonPatriot I would be suprised if he wasn’t...,1728855562,PW,False,en,@iAnonPatriot I would be suprised if he wasn’t...,0,0,1,...,[],"[{'id_str': '1389833864122613761', 'name': 'Am...",[],PW,False,PW,PW,"{'id': 1802537393842503680, 'id_str': '1802537...",2024-10-13,23
42684,1845580108574155239,@The_Trump_Train B. Early voting. LFG!! MAGA,1728855561,PW,False,en,@The_Trump_Train B. Early voting. LFG!! MAGA,0,0,0,...,[],"[{'id_str': '4102376488', 'name': 'The Trump T...",[],PW,False,PW,PW,"{'id': 1666210848774184975, 'id_str': '1666210...",2024-10-13,23
42685,1845580107018330227,@TeamTrump I just received a Red MAGA Cap 💪🏻 ...,1728855561,PW,False,en,@TeamTrump I just received a Red MAGA Cap 💪🏻 ...,0,0,2,...,[],"[{'id_str': '729676086632656900', 'name': 'Tea...",[],PW,False,PW,PW,"{'id': 1062153943, 'id_str': '1062153943', 'ur...",2024-10-13,23
42686,1845580105193799855,@ProjectLincoln Vote Trump on November 5th! 🤣 ...,1728855560,PW,False,en,@ProjectLincoln Vote Trump on November 5th! 🤣 ...,0,0,0,...,[],"[{'id_str': '1205226529455632385', 'name': 'Th...",[],PW,False,PW,PW,"{'id': 1730980875267883008, 'id_str': '1730980...",2024-10-13,23
42687,1845580103633567789,Oh.\n\nSo MAGA is lying about an assassination...,1728855560,PW,False,en,Oh.\n\nSo MAGA is lying about an assassination...,39,138,546,...,[],[],[],PW,False,PW,PW,"{'id': 1593635660681957399, 'id_str': '1593635...",2024-10-13,23

In [10]:
pd.read_csv("../x-24-us-election/part_47/octobergap_chunk_41.csv.gz")

,type,id,username,text,url,epoch,id_str,lang,rawContent,replyCount,...,sourceUrl,sourceLabel,media,card,cashtags,viewCount,place,user,epoch_dt,date
0,tweet-,1846315208911790107,EliasGo84672692,#trump Donald Trump Followers Left Stranded in...,https://twitter.com/EliasGo84672692/status/184...,1729030823,1846315208911790107,en,#trump Donald Trump Followers Left Stranded in...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1297664230490021888, 'id_str': '1297664...",2024-10-15 22:20:23,2024-10-15
1,tweet-,1846315208064577748,MAGA_GMENGRL,@greg_price11 And nothing is going to happen,https://twitter.com/MAGA_GMENGRL/status/184631...,1729030823,1846315208064577748,en,@greg_price11 And nothing is going to happen,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1598789111841755153, 'id_str': '1598789...",2024-10-15 22:20:23,2024-10-15
2,tweet-,1846315206831386694,ArdenUltraMAGA,@IvankaNews_ Yes. Why should she get out of an...,https://twitter.com/ArdenUltraMAGA/status/1846...,1729030822,1846315206831386694,en,@IvankaNews_ Yes. Why should she get out of an...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1823141569823739904, 'id_str': '1823141...",2024-10-15 22:20:22,2024-10-15
3,tweet-,1846315204205752737,MAGASknew,Massive 2020 facts,https://twitter.com/MAGASknew/status/184631520...,1729030822,1846315204205752737,en,Massive 2020 facts,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 601524877, 'id_str': '601524877', 'url'...",2024-10-15 22:20:22,2024-10-15
4,tweet-,1846315197335851266,tommyscanz30,🚂🚂TUESDAY GAIN TRAIN!!🚂🚂\n💥💥#MAGA💥💥\n👊~do you ...,https://twitter.com/tommyscanz30/status/184631...,1729030820,1846315197335851266,en,🚂🚂TUESDAY GAIN TRAIN!!🚂🚂\n💥💥#MAGA💥💥\n👊~do you ...,21,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1828957551263633408, 'id_str': '1828957...",2024-10-15 22:20:20,2024-10-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,tweet-,1844877837330772361,RpsAgainstTrump,NEW\n\nDonald Trump’s campaign requested milit...,https://twitter.com/RpsAgainstTrump/status/184...,1728688127,1844877837330772361,en,NEW\n\nDonald Trump’s campaign requested milit...,598,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1221462414744596483, 'id_str': '1221462...",2024-10-11 23:08:47,2024-10-11
49996,tweet-,1844877827960864929,Frida_Goman,@catturd2 One of my greatest achievements is t...,https://twitter.com/Frida_Goman/status/1844877...,1728688125,1844877827960864929,en,@catturd2 One of my greatest achievements is t...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 774657520845541376, 'id_str': '77465752...",2024-10-11 23:08:45,2024-10-11
49997,tweet-,1844877823544263146,DonaldTrumpGFan,@SoHaiB__0 Pata nahi,https://twitter.com/DonaldTrumpGFan/status/184...,1728688123,1844877823544263146,tl,@SoHaiB__0 Pata nahi,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1179839318044692485, 'id_str': '1179839...",2024-10-11 23:08:43,2024-10-11
49998,tweet-,1844877819056177335,stevenaltepete1,Really this crap is now in my feed good God an...,https://twitter.com/stevenaltepete1/status/184...,1728688122,1844877819056177335,en,Really this crap is now in my feed good God an...,3,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1232855919639384064, 'id_str': '1232855...",2024-10-11 23:08:42,2024-10-11
49999,tweet-,1844877813721203042,AllEyezonMon,@oh_HOLMES @JohnWilson @BanUnsweetTea this is ...,https://twitter.com/AllEyezonMon/status/184487...,1728688121,1844877813721203042,en,@oh_HOLMES @JohnWilson @BanUnsweetTea this is ...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1696155802589904897, 'id_str': '1696155...",2024-10-11 23:08:41,2024-10-11

In [18]:
df[df['retweetedTweet'] == True]

Empty DataFrame
Columns: [Unnamed: 0, id, text, url, epoch, media, retweetedTweet, retweetedTweetID, retweetedUserID, id_str, lang, rawContent, replyCount, retweetCount, likeCount, quoteCount, conversationId, conversationIdStr, hashtags, mentionedUsers, links, viewCount, quotedTweet, in_reply_to_screen_name, in_reply_to_status_id_str, in_reply_to_user_id_str, location, cash_app_handle, user, date, _type, type]
Index: []

[0 rows x 32 columns]

In [36]:
octber = pd.read_csv('../x-24-us-election/part_19/may_july_chunk_380.csv.gz', low_memory=False)

In [37]:
octber['date'] = pd.to_datetime(octber['date'])
min_rows = octber[octber['date'] == octber['date'].min()]

In [38]:
min_rows

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
36901,36901,1653186904198619137,My Loyalty Isn't Joe Biden. ! ?,https://twitter.com/twisterbolt/status/1653186...,1.682985e+09,[],False,NaN,NaN,1653186904198619137,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 75473131, 'id_str': '75473131', 'url': ...",2023-05-01,NaN,tweet-
36902,36902,1653186884749721604,My Loyalty Is Not Joe Biden. ! ?,https://twitter.com/twisterbolt/status/1653186...,1.682985e+09,[],False,NaN,NaN,1653186884749721604,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 75473131, 'id_str': '75473131', 'url': ...",2023-05-01,NaN,tweet-
36903,36903,1653186829317701633,My Loyalty Isn't Donald Trump. ! ?,https://twitter.com/twisterbolt/status/1653186...,1.682985e+09,[],False,NaN,NaN,1653186829317701633,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 75473131, 'id_str': '75473131', 'url': ...",2023-05-01,NaN,tweet-
36904,36904,1653186811278098433,My Loyalty Is Not Donald Trump. ! ?,https://twitter.com/twisterbolt/status/1653186...,1.682985e+09,[],False,NaN,NaN,1653186811278098433,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 75473131, 'id_str': '75473131', 'url': ...",2023-05-01,NaN,tweet-
36905,36905,1653187111288295425,What's up with plywood prices? \nConsistent li...,https://twitter.com/MojoUprising/status/165318...,1.682985e+09,[],False,NaN,NaN,1653187111288295425,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 335493027, 'id_str': '335493027', 'url'...",2023-05-01,NaN,tweet-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40886,40886,1652825193927041025,#NoTePierdas Biden anuncia que se presentará a...,https://twitter.com/14ymedio/status/1652825193...,1.682899e+09,"[{'display_url': 'pic.x.com/fi2jen6fhp', 'expa...",False,NaN,NaN,1652825193927041025,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 2295056168, 'id_str': '2295056168', 'ur...",2023-05-01,NaN,tweet-
40887,40887,1652825513226911745,"Gano Itapúa, Perdió el Paraguay",https://twitter.com/_magalialarcon/status/1652...,1.682899e+09,[],False,NaN,NaN,1652825513226911745,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 2983289447, 'id_str': '2983289447', 'ur...",2023-05-01,NaN,tweet-
40888,40888,1652825314886664192,"Paraguay, presidential election, preliminary r...",https://twitter.com/AmericaElige/status/165282...,1.682899e+09,"[{'display_url': 'pic.x.com/6ckh4szzfa', 'expa...",False,NaN,NaN,1652825314886664192,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1174279378802532352, 'id_str': '1174279...",2023-05-01,NaN,tweet-
40889,40889,1652825157352800256,Freedom of the Press takes center stage at ann...,https://twitter.com/NTVNEWS/status/16528251573...,1.682899e+09,[],False,NaN,NaN,1652825157352800256,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 4500691, 'id_str': '4500691', 'url': 'h...",2023-05-01,NaN,tweet-
40890,40890,1652825156832698368,Chapter 1: A Brave Terrifying New World Part 3...,https://twitter.com/angryconserva13/status/165...,1.682899e+09,[],False,NaN,NaN,1652825156832698368,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1402441415783849991, 'id_str': '1402441...",2023-05-01,NaN,tweet-

In [34]:
octber

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
0,0,1811365251398455347,@2RawTooReal please let the world know about o...,https://twitter.com/pottersquash/status/181136...,1.720698e+09,[],False,NaN,NaN,1811365251398455347,...,True,2RawTooReal,NaN,1.279456e+18,NaN,NaN,"{'id': 45236632, 'id_str': '45236632', 'url': ...",2024-07-11,NaN,tweet-
1,1,1811365251373285464,https://t.co/vaX9JDcgsA,https://twitter.com/EvaSudden/status/181136525...,1.720698e+09,[],False,NaN,NaN,1811365251373285464,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1593622276808871938, 'id_str': '1593622...",2024-07-11,NaN,tweet-
2,2,1811365250887000163,"""Biden’s political position is rapidly deterio...",https://twitter.com/Thai3000dpn/status/1811365...,1.720698e+09,[],False,NaN,NaN,1811365250887000163,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1524868775115313152, 'id_str': '1524868...",2024-07-11,NaN,tweet-
3,3,1811365250060476652,@ObamaClintonDem I'm voting for Biden more tha...,https://twitter.com/mr_frenchie69/status/18113...,1.720698e+09,[],False,NaN,NaN,1811365250060476652,...,False,ObamaClintonDem,1.811083e+18,4.813987e+09,NaN,NaN,"{'id': 1297707907698614273, 'id_str': '1297707...",2024-07-11,NaN,tweet-
4,4,1811365249456410833,@iamchanteezy Count me as one of other 1/2 of ...,https://twitter.com/Marycel74536655/status/181...,1.720698e+09,[],False,NaN,NaN,1811365249456410833,...,False,iamchanteezy,1.811080e+18,4.297203e+07,NaN,NaN,"{'id': 1424884613495902209, 'id_str': '1424884...",2024-07-11,NaN,tweet-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,49995,1811287608716091802,@JoJoFromJerz Wow. Jo. Wow. Did you watch B...,https://twitter.com/reubenoster/status/1811287...,1.720680e+09,[],False,NaN,NaN,1811287608716091802,...,False,JoJoFromJerz,1.811164e+18,8.188931e+17,NaN,NaN,"{'id': 1747739008971526144, 'id_str': '1747739...",2024-07-11,NaN,tweet-
49994,49996,1811287608003067916,Si aún creen en una solución electoral (ja) ti...,https://twitter.com/fantocha__/status/18112876...,1.720680e+09,[],False,NaN,NaN,1811287608003067916,...,False,fantocha__,1.811287e+18,3.653554e+08,NaN,NaN,"{'id': 365355446, 'id_str': '365355446', 'url'...",2024-07-11,NaN,tweet-
49995,49997,1811287606417830394,@MagaHAT_ETH bullish on trump\n\n$MAGA,https://twitter.com/manwithlucky/status/181128...,1.720680e+09,[],False,NaN,NaN,1811287606417830394,...,False,MAGACoinX,1.811194e+18,1.785953e+18,NaN,NaN,"{'id': 238433416, 'id_str': '238433416', 'url'...",2024-07-11,NaN,tweet-
49996,49998,1811287600449339475,@VivekGRamaswamy Biden has an easy win. He can...,https://twitter.com/cubancha/status/1811287600...,1.720680e+09,"[{'display_url': 'pic.x.com/r0b5QDd3MA', 'expa...",False,NaN,NaN,1811287600449339475,...,False,VivekGRamaswamy,1.811235e+18,1.227800e+18,NaN,NaN,"{'id': 1661462045521510406, 'id_str': '1661462...",2024-07-11,NaN,tweet-
49997,49999,1811287600348697022,@acnewsitics https://t.co/t36swTy5Tw,https://twitter.com/GrifterJBiden/status/18112...,1.720680e+09,"[{'display_url': 'pic.x.com/t36swTy5Tw', 'expa...",False,NaN,NaN,1811287600348697022,...,False,acnewsitics,1.810772e+18,1.080188e+18,NaN,NaN,"{'id': 1697618674201333760, 'id_str': '1697618...",2024-07-11,NaN,tweet-

In [35]:
octber[octber['retweetedTweet'] == '1811339675384357201']

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
23035,23037,24,5,7,0.0,1811339675384357201,1811339675384357201,[],"[{'id_str': '928060984379441152', 'name': 'sha...",[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01,NaN,tweet-